[package]
name = "cap-camera-windows"
version = "0.1.0"
edition = "2024"

[dependencies]
ffmpeg = { workspace = true }
cap-camera-mediafoundation = { path = "../camera-mediafoundation" }
cap-camera-directshow = { path = "../camera-directshow" }

windows = { workspace = true, features = ["Win32_Media_MediaFoundation"] }
windows-core = { workspace = true }
thiserror.workspace = true
inquire = "0.7.5"

[lints]
workspace = true

[dev-dependencies]
inquire = "0.7.5"
