[package]
name = "cap-recording"
version = "0.1.0"
edition = "2021"

[dependencies]
cap-project = { path = "../project" }
cap-media = { path = "../media" }
cap-flags = { path = "../flags" }

specta.workspace = true
# TODO(Ilya): remove when specta releases rc.21
specta-util.workspace = true
tokio.workspace = true
flume.workspace = true
thiserror.workspace = true

serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4.38"
tracing = "0.1.40"
device_query = "2.1.0"
image = "0.25.2"
either = "1.13.0"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.26.0"
objc = "0.2.7"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = [
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
  "Win32_UI_WindowsAndMessaging",
] }
