[package]
name = "ffmpeg-hw-device"
version = "0.1.0"
edition = "2024"

[dependencies]
ffmpeg.workspace = true
tracing.workspace = true
workspace-hack = { version = "0.1", path = "../workspace-hack" }

[lints]
workspace = true
