[package]
name = "cap-quicklook-thumbnailing"
version = "0.1.0"
edition = "2024"

[target.'cfg(target_os = "macos")'.dependencies]
objc2.workspace = true
block2 = "0.6.2"
objc2-foundation = "0.3.2"
objc2-quick-look-thumbnailing = "0.3.2"

[lints]
workspace = true
