[package]
name = "scap-screencapturekit"
version = "0.1.0"
edition = "2024"


[dependencies]
futures = { workspace = true }
tracing = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
cidre = { workspace = true }
objc2 = "0.6.1"
objc2-app-kit = "0.3.1"
objc2-foundation = "0.3.1"

[lints]
workspace = true

[dev-dependencies]
clap = { version = "4.5.40", features = ["derive"] }
inquire = "0.7.5"
