[package]
name = "cap-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
cap-project = { path = "../project" }
cap-ffmpeg = { path = "../ffmpeg" }
cap-rendering = { path = "../rendering" }

tokio = { version = "1.39.2", features = ["macros", "process", "fs"] }
tracing = "0.1.40"
cpal.workspace = true
serde_json = "1.0.128"
axum = { version = "0.7.5", features = ["ws"] }
ffmpeg.workspace = true
specta = "=2.0.0-rc.19"
serde = { version = "1", features = ["derive"] }
