[package]
name = "cap-editor"
version = "0.1.0"
edition = "2021"

[dependencies]

cap-media = { path = "../media" }
cap-project = { path = "../project" }
cap-rendering = { path = "../rendering" }

tokio = { workspace = true, features = ["macros", "process", "fs"] }
cpal.workspace = true
axum = { version = "0.7.5", features = ["ws"] }
ffmpeg.workspace = true
specta.workspace = true
serde = { version = "1", features = ["derive"] }
sentry.workspace = true
futures = "0.3.31"
tracing = "0.1.41"
flume.workspace = true
