name: Tinybird CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - master
    # paths:
    #   - 'tinybird/**' # TODO: Reenable this
    types: [opened, reopened, labeled, unlabeled, synchronize]

concurrency: ${{ github.workflow }}-${{ github.event.pull_request.number }}

permissions:
  contents: read

env:
  TINYBIRD_HOST: ${{ secrets.TINYBIRD_HOST }}
  TINYBIRD_TOKEN: ${{ secrets.TINYBIRD_TOKEN }}

jobs:
  ci:
    name: Validate
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'tinybird'
    services:
      tinybird:
        image: tinybirdco/tinybird-local:latest
        ports:
          - 7181:7181
    steps:
      - uses: actions/checkout@v3

      - name: Install Tinybird CLI
        run: curl https://tinybird.co | sh

      - name: Build project
        run: tb build

      - name: Test project
        run: tb test run

      - name: Check auth
        run: tb --host ${{ secrets.TINYBIRD_HOST }} --token ${{ secrets.TINYBIRD_TOKEN }} auth info

      - name: DEBUG
        run: tb --cloud --host ${{ env.TINYBIRD_HOST }} --token ${{ env.TINYBIRD_TOKEN }} info && echo "$TINYBIRD_HOST $TINYBIRD_TOKEN"

      - name: Deployment check
        run: tb --cloud --host ${{ env.TINYBIRD_HOST }} --token ${{ env.TINYBIRD_TOKEN }} deploy --check
